name: ArmedWars
version: '1.0-SNAPSHOT'
main: me.owls.armedwars.ArmedWars

commands:
  armedwars:
    description:
    permission: armedwars.commands
    aliases: aw

permissions:
  armedwars.commands:
    default: op
    description: "Access to the '/aw'"